class apiTranslateDict:
    financetoNewsIndustry = {
        'Medical Diagnostics & Research':'Medical Laboratories & Research',
        'Retail - Apparel & Specialty':'Specialty Retail, Other',
        'Biotechnology':'Biotechnology',
        'Consulting & Outsourcing':'Staffing & Outsourcing Services',
        'Drug Manufacturers': 'Drug Manufacturers - Major',
        'Insurance - Property & Casualty': 'Property & Casualty Insurance',
        'Online Media':'Internet Software & Services',
        'Insurance':'Insurance Brokers',
        'Application Software':'Application Software',
        'Medical Devices':'Medical Appliances & Equipment',
        'Oil & Gas - E&P':'Oil & Gas Equipment & Services',
        'Brokers & Exchanges':'Investment Brokerage - National',
        'Semiconductors':'Semiconductor - Integrated Circuits',
        'Credit Services':'Credit Services',
        'Airlines':'Major Airlines',
        'Tobacco Products':'Tobacco Products, Other',
        'Medical Distribution':'Medical Instruments & Supplies',
        'Chemicals':'Chemicals - Major Diversified',
        'Health Care Plans':'Health Care Plans',
        'Utilities - Regulated':'Diversified Utilities',
        'Industrial Products':'Industrial Equipment Wholesale',
        'Insurance—Life':'Life Insurance',
        'Packaging & Containers':'Packaging & Containers',
        'Communication Services':'Diversified Communication Services',
        'Computer Hardware':'Diversified Computer Systems',
        'REITs':'REIT - Diversified',
        'Asset Management':'Asset Management',
        "Oil & Gas - Refining & Marketing":"Oil & Gas Refining & Marketing",
        'Industrial Distribution':'Industrial Equipment Wholesale',
        'Agricultural Inputs':'Farm Products',
        'Transportation & Logistics':'Trucking',
        'REIT   Healthcare Facilities': 'REIT - Healthcare Facilities',
        'Specialty Chemicals':'Specialty Chemicals',
        'Oil & Gas - Integrated':'Major Integrated Oil & Gas',
        'Beverages - Non-Alcoholic':'Beverages - Soft Drinks',
        'Health Care Providers':'Healthcare Information Services',
        'Metals & Mining':'Industrial Metals & Minerals',
        'Oil & Gas - Midstream':'Independent Oil & Gas',
        'Engineering & Construction':'Heavy Construction',
        'Manufacturing - Apparel & Furniture':'Textile - Apparel Clothing',
        'Medical Instruments & Equipment':'Medical Appliances & Equipment',
        'Autos': 'Auto Manufacturers - Major',
        'Employment Services':'General Contractors',
        'Insuranceâ€”Diversified':'Insurance Brokers',
        'Agriculture':'Farm Products',
        'Homebuilding & Construction':'Residential Construction',
        'Truck Manufacturing':'Trucks & Other Vehicles',
        'Advertising & Marketing Services':'Advertising Agencies',
        'Apparel Manufacturing':'Textile - Apparel Clothing',
        'Retail - Defensive':'Specialty Retail, Other',
        'Software—Infrastructure':'Technical & System Software',
        'Aerospace & Defense':'Aerospace/Defense - Major Diversified',
        'Travel & Leisure':'Lodging',
        'Business Services':'Business Services',
        'Beverages - Alcoholic':'Beverages - Wineries & Distillers',
        'Utilities—Regulated Electric':'Electric Utilities',
        'Farm & Construction Machinery':'Farm & Construction Machinery',
        'Banks   Regional':'Regional - Mid-Atlantic Banks',
        'Oil & Gas Equipment & Services':'Major Integrated Oil & Gas',
        'Oil & Gas - Drilling':'Oil & Gas Drilling & Exploration',
        'Insurance - Specialty':'Surety & Title Insurance',
        'Beveragesâ€”Wineries & Distilleries':'Beverages - Brewers',
        'Banks':'Money Center Banks',
        'Entertainment':'Entertainment - Diversified',
        'Consumer Packaged Goods':'Processed & Packaged Goods',
        'None':'Wireless Communications',
        'Waste Management':'Waste Management',
        'Utilities - Independent Power Producers':'Insurance Brokers',
        'Restaurants':'Restaurants',
        'Conglomerates':'Conglomerates',
        'Real Estate Services':'Real Estate Development',
        'Forest Products':'Lumber, Wood Production',
        'Oil & Gas - Services':"Oil & Gas Equipment & Services",
        'Building Materials':'Building Materials Wholesale',
        'Steel':'Steel & Iron',
        'Communication Equipment':'Communication Equipment',
        'Personal Services':'Personal Services',
        'Insurance - Life':'Life Insurance'}
    def getFinanceToNewsIndustry(self):
        return self.financetoNewsIndustry